version: '2'
services:
  php56:
    build: ./docker/php56
    depends_on: [db]
    volumes:
      - ./code:/test_simplified
    links: [db]
  db:
    image: mongo
  proxy:
    image: nginx:stable-alpine
    depends_on: [php56]
    links: [php56]
    ports:
      - "8888:80"
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/conf.d/default.conf